# github repository Actions 페이지에 나타낼 이름
name: CI/CD

# event trigger
on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:

    ## jdk setting
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # https://github.com/actions/setup-java

    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    ## gradle build
    - name: Change gradlew permissions
      run: chmod +x ./gradlew
      
    - name: Buid with Gradle
      run: ./gradlew build -x test
    
    ## make garamgaebi-firebase-secret.json
    - name: make garamgaebi-firebase-secret.json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "gcp.json"
        json: ${{ secrets.FIREBASE_SECRET }}
        dir: './src/main/resources'

    ## docker build & push to production
    - name: Docker build & push to prod
      if: contains(github.ref, 'dev')
      run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker build -t ${{ secrets.DOCKER_REPO }} .
          sudo docker push ${{ secrets.DOCKER_REPO }}

    # ## deploy to production
    # - name: Deploy to prod
    #   uses: appleboy/ssh-action@master
    #   id: deploy-prod
    #   if: contains(github.ref, 'dev')
    #   with:
    #       host: ${{ secrets.HOST_PROD }}
    #       username: ec2-user
    #       key: ${{ secrets.PRIVATE_KEY }}
    #       envs: GITHUB_SHA
    #       script: |
    #           sudo docker rm -f $(docker ps -qa)
    #           sudo docker pull ${{ secrets.DOCKER_REPO }}/garamgaebi-dev
    #           sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_REPO }}/garamgaebi-dev
